### ISSUE TITLE
No service for type 'SupportTicketApi.Data.Contexts.TicketContext' has been registered

### ISSUE THREAD

**Issue by felaray** [MicrosoftDocs/aspire-docs-samples#1]
Hi, I followed the tutorial, but I have this issue.

"System.InvalidOperationException: 'No service for type 'SupportTicketApi.Data.Contexts.TicketContext' has been registered.'"

Do I need to register TicketContext in SupportTicketApi.MigrationService? 

![image](https://github.com/MicrosoftDocs/aspire-docs-samples/assets/5403865/5a7fff98-f4f1-44cd-9dc6-6f64d7a1922d)

**Comment by CamSoper** [comment]
@felaray Yep! Sorry, my bad. I've updated the doc here: https://github.com/dotnet/docs-aspire/pull/1443
